events {}

http {
    server {
        listen 80;

        location / {
            root /home/ubuntu/app/frontend;
            index index.html;
        }

        location /api/ {
            proxy_pass http://localhost:5000/;
        }
    }
}
